apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hba3anaay-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hba3anaay-nodejs 
  name: hba3anaay-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: hba3anaay-nodejs 
